# stage 2 docker-compose.yml
web:
    image: "demo_stage2"
    volumes:
     - ./dj_demo/dj_demo/docker_settings.py:/code/dj_demo/settings.py
    links:
     - db:db
    ports:
     - "5000:8000"
    command: ./entry-point.sh 

db:
    image: "mysql:5.6"
    environment:
     - MYSQL_ROOT_PASSWORD=password
     - MYSQL_DATABASE=demo
