# stage 3 docker-compose.yml
rproxy:
    image: "nginx:1.9"
    ports:
     - "5000:5000"
    volumes:
     - ./nginx.conf:/etc/nginx/nginx.conf:ro 
    links:
     - web:web

web:
    image: "demo_stage2"
    volumes:
     - ./dj_demo/dj_demo/docker_settings.py:/code/dj_demo/settings.py
    links:
     - db:db
    command: ./entry-point.sh 

db:
    image: "mysql:5.6"
    environment:
     - MYSQL_ROOT_PASSWORD=password
     - MYSQL_DATABASE=demo
